# Generated by Django 2.2.1 on 2019-06-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_interested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='num_unit',
            new_name='num_units',
        ),
    ]
